<?php
/**
 * ACF Custom fields and options page for the theme
 *
 * @package wanda
 */

 add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_69c57058aed3e',
	'title' => 'Campi per Edizione (POST)',
	'fields' => array(
		array(
			'key' => 'field_69c5708b6d88b',
			'label' => 'Dati evento',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_69c570a06d88c',
			'label' => 'Luogo',
			'name' => 'edizione_luogo',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Teatro Wanda Capodaglio, Via Roma, 36, 52020 Castelfranco Piandiscò AR',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_69c7ed3df8267',
			'label' => 'Data evento',
			'name' => 'edizione_data_serata',
			'aria-label' => '',
			'type' => 'date_time_picker',
			'instructions' => 'Data e orario di inizio della serata',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd F Y H:i',
			'return_format' => 'Y-m-d H:i:s',
			'first_day' => 1,
			'default_to_current_date' => 0,
			'allow_in_bindings' => 0,
		),
		array(
			'key' => 'field_69c816821900a',
			'label' => 'Promosso Da',
			'name' => 'edizione_promosso_da',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => 'Includi anche Associazone Culturale Wanda Capodaglio',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '<a href="https://associazioneculturalewandacapodaglio.it" target="_blank" rel="noopener nofollow noreferrer">Associazione Culturale Wanda Capodaglio</a> <br> <a href="https://associazioneculturalemasaccio.com/" target="_blank" rel="noopener nofollow noreferrer">Associazione Culturale Masaccio</a>',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 1,
			'delay' => 1,
		),
		array(
			'key' => 'field_69c81ef615eb7',
			'label' => 'Ingresso',
			'name' => 'edizione_ingresso',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'Chi promuove l\'evento (includi anche Ass.Cul. Wanda Capodaglio)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Ingresso libero su prenotazione. Per info: [contatto email] o tel: [contatto numero_di_telefono]',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_69c571606d88f',
			'label' => 'Programma',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_69c571c06d890',
			'label' => 'Presentatore',
			'name' => 'edizione_presentatore',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Nome e cognome (es: Lorenzo Giusti)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => 'Presenta:',
			'append' => '',
		),
		array(
			'key' => 'field_69c571ea6d891',
			'label' => 'Esibizione',
			'name' => 'edizione_esibizione',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => 'Scuole che si esibiscono prima dei finalisti (es: "Scuola di musica di Fiesole fondazione Onlus")',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 1,
			'delay' => 1,
		),
		array(
			'key' => 'field_69c572406d892',
			'label' => 'Esibizione Finalisti',
			'name' => 'edizione_finalisti',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => 'Esibizione dei finalisti, nomi in fila. Es:\nMario Rossi, Giovanna Verdi, Luigi Bianchi',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 1,
			'delay' => 1,
		),
		array(
			'key' => 'field_69c572956d893',
			'label' => 'Altre informazioni',
			'name' => 'edizione_altre_informazioni',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => 'Per altre informazioni varie, es:\nA cura di..., In ricordo di...',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 1,
			'delay' => 1,
		),
		array(
			'key' => 'field_22c82e99doe14',
			'label' => 'Giuria',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_69c572d46d894',
			'label' => 'Giuria',
			'name' => 'edizione_giuria_wysiwyg',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => 'Informazioni sulla giuria (testo prima della lista di giudici)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 1,
			'delay' => 1,
		),
		array(
			'key' => 'field_69c82d93dae28',
			'label' => 'Giuria',
			'name' => 'edizione_giuria_relationship',
			'aria-label' => '',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'giudice',
			),
			'post_status' => array(
				0 => 'publish',
			),
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
				1 => 'taxonomy',
			),
			'return_format' => 'object',
			'min' => '',
			'max' => '',
			'allow_in_bindings' => 0,
			'elements' => '',
			'bidirectional' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_69c572f86d895',
			'label' => 'Commissione di preselezione',
			'name' => 'edizione_commissione_relationship',
			'aria-label' => '',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'giudice',
			),
			'post_status' => array(
				0 => 'publish',
			),
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
				1 => 'taxonomy',
			),
			'return_format' => 'object',
			'min' => '',
			'max' => '',
			'allow_in_bindings' => 0,
			'elements' => '',
			'bidirectional' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_33c81e09adf14',
			'label' => 'Finalisti',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_69cc2c093847e',
			'label' => 'Finalisti',
			'name' => 'edizione_finalisti_list',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => 'Seleziona i finalisti dell\'edizione',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'pagination' => 0, //  may need to be changed to 1 for larger lists
			'min' => 0,
			'max' => 0,
			'collapsed' => 'field_69cc2c2d3847f',
			'button_label' => 'Aggiungi Finalista',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_69cc2c2d3847f',
					'label' => 'Finalista',
					'name' => 'finalista',
					'aria-label' => '',
					'type' => 'relationship',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'finalista',
					),
					'post_status' => array(
						0 => 'publish',
					),
					'taxonomy' => '',
					'filters' => array(
						0 => 'search',
						1 => 'taxonomy',
					),
					'return_format' => 'object',
					'min' => 1,
					'max' => 1,
					'allow_in_bindings' => 0,
					'elements' => '',
					'bidirectional' => 0,
					'bidirectional_target' => array(
					),
					'parent_repeater' => 'field_69cc2c093847e',
				),
				array(
					'key' => 'field_69cc2c4c38480',
					'label' => 'Posizione in classifica',
					'name' => 'posizione_in_classifica',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						1 => '1° Classificato',
						2 => '2° Classificato',
						3 => '3° Classificato',
						0 => 'Partecipante',
					),
					'default_value' => 0,
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'allow_in_bindings' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'create_options' => 0,
					'save_options' => 0,
					'parent_repeater' => 'field_69cc2c093847e',
				),
			),
		),
		array(
			'key' => 'field_69c5735053c86',
			'label' => 'Documenti',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_69c5739253c88',
			'label' => 'Regolamento (testo)',
			'name' => 'edizione_regolamento',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 1,
		),
		array(
			'key' => 'field_69c5735b53c87',
			'label' => 'Regolamento (documento scaricabile)',
			'name' => 'edizione_regolamento_file',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'pdf, doc, docx',
			'allow_in_bindings' => 0,
		),
		array(
			'key' => 'field_69c573bd53c89',
			'label' => 'Catalogo',
			'name' => 'edizione_catalogo_file',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'pdf',
			'allow_in_bindings' => 0,
		),
		array(
			'key' => 'field_69c5784246fab',
			'label' => 'Sponsor',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_69c579910beeb',
			'label' => 'Patrocini',
			'name' => 'edizione_lista_patrocini',
			'aria-label' => '',
			'type' => 'gallery',
			'instructions' => 'Loghi degli enti patrocinatori',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min' => '',
			'max' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'png,jpg,jpeg,webp',
			'insert' => 'append',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_69c579d70beec',
			'label' => 'Sostenitori',
			'name' => 'edizione_lista_sostenitori',
			'aria-label' => '',
			'type' => 'gallery',
			'instructions' => 'Loghi dei sostenitori privati',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min' => '',
			'max' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'png,jpg,jpeg,webp',
			'insert' => 'append',
			'preview_size' => 'medium',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'edizione',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
) );


// === DEPRECATED FINALISTA FIELDS ===
// acf_add_local_field_group( array(
// 	'key' => 'group_69c575ec82a6b',
// 	'title' => 'Campi per Finalisti (POST)',
// 	'fields' => array(
// 		array(
// 			'key' => 'field_69c575ec8b090',
// 			'label' => 'Vincitore',
// 			'name' => 'finalista_ha_vinto_concorso',
// 			'aria-label' => '',
// 			'type' => 'true_false',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'message' => 'Ha vinto il concorso',
// 			'default_value' => 0,
// 			'allow_in_bindings' => 0,
// 			'ui' => 0,
// 			'ui_on_text' => '',
// 			'ui_off_text' => '',
// 		),
// 		array(
// 			'key' => 'field_69c57a3d9bee4',
// 			'label' => 'Posizione in classifica',
// 			'name' => 'finalista_posizione_in_classifica',
// 			'aria-label' => '',
// 			'type' => 'text',
// 			'instructions' => '1º classificato – 1ª classificata',
// 			'required' => 0,
// 			'conditional_logic' => array(
// 				array(
// 					array(
// 						'field' => 'field_69c575ec8b090',
// 						'operator' => '==',
// 						'value' => '1',
// 					),
// 				),
// 			),
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'maxlength' => '',
// 			'allow_in_bindings' => 0,
// 			'placeholder' => '',
// 			'prepend' => '',
// 			'append' => '',
// 		),
// 	),
// 	'location' => array(
// 		array(
// 			array(
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'finalista',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'normal',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => true,
// 	'description' => '',
// 	'show_in_rest' => 0,
// 	'display_title' => '',
// ) );


acf_add_local_field_group( array(
	'key' => 'group_69c82d4abfca0',
	'title' => 'Campi per Giudice (POST)',
	'fields' => array(
		array(
			'key' => 'field_69c82d4bd09e4',
			'label' => 'Tipo di giuria',
			'name' => 'tipo_di_giuria',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'giuria' => 'Giuria',
				'selezione' => 'Giuria di selezione',
			),
			'default_value' => 'giuria',
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'allow_in_bindings' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'create_options' => 0,
			'save_options' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'giudice',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
) );

	acf_add_local_field_group( array(
	'key' => 'group_69c5765eb8289',
	'title' => 'Campi per Informazioni Sito (OPTIONS)',
	'fields' => array(
		array(
			'key' => 'field_69c6a9e7a6457',
			'label' => 'Data scadenza iscrizioni',
			'name' => 'data_scadenza_iscrizioni',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => 'Quando si svolgerà il concorso di quest\'anno. Viene usato dal tema per mostrare alcuni',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y',
			'return_format' => 'Ymd',
			'first_day' => 1,
			'default_to_current_date' => 1,
			'allow_in_bindings' => 0,
		),
		array(
			'key' => 'field_69c6af0e37a13',
			'label' => 'Mostra countdown iscrizioni',
			'name' => 'mostra_countdown',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Mostra un countdown alla chiusura delle iscrizioni',
			'default_value' => 0,
			'allow_in_bindings' => 0,
			'ui_on_text' => 'Mostra',
			'ui_off_text' => 'Non mostrare',
			'ui' => 1,
		),
		array(
			'key' => 'field_69c5765fa1891',
			'label' => 'Banner',
			'name' => 'banner',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_69c57686a1892',
					'label' => 'testo',
					'name' => 'testo',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Si ricorda che la data ultima per presentare la propria candidatura è il [data_ultima]',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_69c576c3a1893',
					'label' => 'Banner attivo',
					'name' => 'banner_is_active',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Mostra il banner',
					'default_value' => 0,
					'allow_in_bindings' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
		),
		array(
			'key' => 'field_69c5770655f17',
			'label' => 'Copyright',
			'name' => 'copyright',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Copyright © 2025-2026 Associazione Culturale Wanda Capodaglio | Concorso Nazionale di Teatro',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_69c57723322ab',
			'label' => 'Contatti',
			'name' => 'contatti',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_69c5776a322ac',
					'label' => 'Email',
					'name' => 'email',
					'aria-label' => '',
					'type' => 'email',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_69c57773322ad',
					'label' => 'Numero di telefono',
					'name' => 'numero_di_telefono',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
		array(
			'key' => 'field_69c577bbfce98',
			'label' => 'BANDO',
			'name' => 'bando',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => 'PDF del bando per l\'edizione di quest\'anno',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'pdf, doc, docx',
			'allow_in_bindings' => 0,
		),
		array(
			'key' => 'field_69c7cd950c127',
			'label' => 'Breve descrizione del sito (footer)',
			'name' => 'breve_descrizione_del_sito',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => 250,
			'allow_in_bindings' => 0,
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_69c57cdd8c59d',
			'label' => 'Testi Homepage',
			'name' => 'homepage',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_69c57cf28c59e',
					'label' => 'Contenuto principale',
					'name' => 'descrizione_del_sito',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
				array(
					'key' => 'field_69c57d3095b24',
					'label' => 'Galleria Foto principale',
					'name' => 'foto_slider_principale',
					'aria-label' => '',
					'type' => 'gallery',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min' => '',
					'max' => '',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'insert' => 'append',
					'preview_size' => 'medium',
				),
				array(
					'key' => 'field_69c57d4e95b25',
					'label' => 'CTA Finale titolo',
					'name' => 'cta_finale_titolo',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_69c57d7695b26',
					'label' => 'CTA Finale testo',
					'name' => 'cta_finale_body',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_69c57d4e95b25',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_69c57d8395b27',
					'label' => 'CTA Finale Foto',
					'name' => 'cta_finale_img',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'allow_in_bindings' => 0,
					'preview_size' => 'medium',
				),
				array(
					'key' => 'field_69c57dba95b29',
					'label' => 'Cta Finale pulsante',
					'name' => 'cta_finale_button_text',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Scopri la storia del Concorso',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_69c57d9495b28',
					'label' => 'Cta Finale LINK',
					'name' => 'cta_finale_link',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_69c57dba95b29',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'informazioni-sito',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
) );
} );

add_action( 'init', function() {
	register_taxonomy( 'tag-edizione', array(
		0 => 'finalista',
		1 => 'giudice',
		2 => 'post',
		3 => 'edizione',
	), array(
		'labels' => array(
			'name' => 'Edizioni Concorso',
			'singular_name' => 'Edizione Concorso',
			'menu_name' => 'Edizione Concorso',
			'all_items' => 'Tutti i tag di edizione concorso',
			'edit_item' => 'Modifica tag di edizione concorso',
			'view_item' => 'Visualizza tag di edizione concorso',
			'update_item' => 'Aggiorna tag di edizione concorso',
			'add_new_item' => 'Aggiungi nuovo tag di edizione concorso',
			'new_item_name' => 'Nome nuovo tag di edizione concorso',
			'search_items' => 'Cerca tag di edizione concorso',
			'popular_items' => 'Tag di edizione concorso più usati',
			'separate_items_with_commas' => 'Separa i tag di edizione concorso con virgole',
			'add_or_remove_items' => 'Aggiungi o rimuovi tag di edizione concorso',
			'choose_from_most_used' => 'Scegli tra i tag di edizione concorso più usati',
			'not_found' => 'Nessun tag di edizione concorso trovata',
			'no_terms' => 'Nessun tag di edizione concorso',
			'items_list_navigation' => 'Navigazione lista tag di edizione concorso',
			'items_list' => 'Lista tag di edizione concorso',
			'back_to_items' => '← Vai alla lista tag di edizione concorso',
			'item_link' => 'Link tag di edizione concorso',
			'item_link_description' => 'Un link al tag di edizione concorso',
		),
		'public' => true,
		'show_in_menu' => true,
		'show_in_rest' => true,
	) );
} );

add_action( 'init', function() {
	register_post_type( 'edizione', array(
	'labels' => array(
		'name' => 'Edizioni',
		'singular_name' => 'Edizione',
		'menu_name' => 'Edizioni',
		'all_items' => 'All Edizioni',
		'edit_item' => 'Edit Edizione',
		'view_item' => 'View Edizione',
		'view_items' => 'View Edizioni',
		'add_new_item' => 'Add Edizione',
		'add_new' => 'Add Edizione',
		'new_item' => 'New Edizione',
		'parent_item_colon' => 'Parent Edizione:',
		'search_items' => 'Search Edizioni',
		'not_found' => 'No edizioni found',
		'not_found_in_trash' => 'No edizioni found in Trash',
		'archives' => 'Edizione Archives',
		'attributes' => 'Edizione Attributes',
		'insert_into_item' => 'Insert into edizione',
		'uploaded_to_this_item' => 'Uploaded to this edizione',
		'filter_items_list' => 'Filter edizioni list',
		'filter_by_date' => 'Filter edizioni by date',
		'items_list_navigation' => 'Edizioni list navigation',
		'items_list' => 'Edizioni list',
		'item_published' => 'Edizione published.',
		'item_published_privately' => 'Edizione published privately.',
		'item_reverted_to_draft' => 'Edizione reverted to draft.',
		'item_scheduled' => 'Edizione scheduled.',
		'item_updated' => 'Edizione updated.',
		'item_link' => 'Edizione Link',
		'item_link_description' => 'A link to a edizione.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-tickets-alt',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
		2 => 'thumbnail',
		3 => 'custom-fields',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'finalista', array(
	'labels' => array(
		'name' => 'Finalisti',
		'singular_name' => 'finalista',
		'menu_name' => 'Finalisti',
		'all_items' => 'All Finalisti',
		'edit_item' => 'Edit finalista',
		'view_item' => 'View finalista',
		'view_items' => 'View Finalisti',
		'add_new_item' => 'Add finalista',
		'add_new' => 'Add finalista',
		'new_item' => 'New finalista',
		'parent_item_colon' => 'Parent finalista:',
		'search_items' => 'Search Finalisti',
		'not_found' => 'No finalisti found',
		'not_found_in_trash' => 'No finalisti found in Trash',
		'archives' => 'finalista Archives',
		'attributes' => 'finalista Attributes',
		'insert_into_item' => 'Insert into finalista',
		'uploaded_to_this_item' => 'Uploaded to this finalista',
		'filter_items_list' => 'Filter finalisti list',
		'filter_by_date' => 'Filter finalisti by date',
		'items_list_navigation' => 'Finalisti list navigation',
		'items_list' => 'Finalisti list',
		'item_published' => 'finalista published.',
		'item_published_privately' => 'finalista published privately.',
		'item_reverted_to_draft' => 'finalista reverted to draft.',
		'item_scheduled' => 'finalista scheduled.',
		'item_updated' => 'finalista updated.',
		'item_link' => 'finalista Link',
		'item_link_description' => 'A link to a finalista.',
	),
	'public' => true,
	'exclude_from_search' => true,
	'show_in_nav_menus' => false,
	'show_in_admin_bar' => false,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-admin-users',
	'supports' => array(
		0 => 'title',
		1 => 'excerpt',
		2 => 'thumbnail',
		3 => 'custom-fields',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'giudice', array(
	'labels' => array(
		'name' => 'Giuria',
		'singular_name' => 'Giudice',
		'menu_name' => 'Giuria',
		'all_items' => 'All Giuria',
		'edit_item' => 'Edit Giudice',
		'view_item' => 'View Giudice',
		'view_items' => 'View Giuria',
		'add_new_item' => 'Add Giudice',
		'add_new' => 'Add Giudice',
		'new_item' => 'New Giudice',
		'parent_item_colon' => 'Parent Giudice:',
		'search_items' => 'Search Giuria',
		'not_found' => 'No giuria found',
		'not_found_in_trash' => 'No giuria found in Trash',
		'archives' => 'Giudice Archives',
		'attributes' => 'Giudice Attributes',
		'insert_into_item' => 'Insert into giudice',
		'uploaded_to_this_item' => 'Uploaded to this giudice',
		'filter_items_list' => 'Filter giuria list',
		'filter_by_date' => 'Filter giuria by date',
		'items_list_navigation' => 'Giuria list navigation',
		'items_list' => 'Giuria list',
		'item_published' => 'Giudice published.',
		'item_published_privately' => 'Giudice published privately.',
		'item_reverted_to_draft' => 'Giudice reverted to draft.',
		'item_scheduled' => 'Giudice scheduled.',
		'item_updated' => 'Giudice updated.',
		'item_link' => 'Giudice Link',
		'item_link_description' => 'A link to a giudice.',
	),
	'public' => true,
	'exclude_from_search' => true,
	'show_in_nav_menus' => false,
	'show_in_admin_bar' => false,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-admin-users',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
		2 => 'excerpt',
		3 => 'thumbnail',
		4 => 'custom-fields',
	),
	'taxonomies' => array(
		0 => 'edizioni-concorso',
	),
	'delete_with_user' => false,
) );
} );

add_action( 'acf/init', function() {
	acf_add_options_page( array(
	'page_title' => 'Informazioni sito',
	'menu_slug' => 'informazioni-sito',
	'position' => '',
	'redirect' => false,
	'menu_icon' => array(
		'type' => 'dashicons',
		'value' => 'dashicons-admin-generic',
	),
	'icon_url' => 'dashicons-admin-generic',
) );
} );

