<?php
/**
 * ACF Custom fields and options page for the theme
 *
 * @package wanda
 */
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_69c57058aed3e',
	'title' => 'Campi per Edizione (POST)',
	'fields' => array(
		array(
			'key' => 'field_69c5708b6d88b',
			'label' => 'Dati evento',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_69c570596d88a',
			'label' => 'Anno',
			'name' => 'anno',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => 1981,
			'max' => 2100,
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'step' => 1,
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_69c570a06d88c',
			'label' => 'Luogo',
			'name' => 'luogo',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Teatro Wanda Capodaglio, Via Roma, 36, 52020 Castelfranco Piandiscò AR',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_69c570e66d88d',
			'label' => 'Giorno',
			'name' => 'giorno',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'giorno e mese (es: 14 Giugno)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_69c571216d88e',
			'label' => 'Ore',
			'name' => 'ore',
			'aria-label' => '',
			'type' => 'range',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '20.00',
			'min' => 0,
			'max' => 24,
			'allow_in_bindings' => 0,
			'step' => '0.01',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_69c571606d88f',
			'label' => 'Programma',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_69c571c06d890',
			'label' => 'Presentatore',
			'name' => 'presentatore',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Nome e cognome (es: Lorenzo Giusti)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => 'Presenta:',
			'append' => '',
		),
		array(
			'key' => 'field_69c571ea6d891',
			'label' => 'Esibizione',
			'name' => 'esibizione',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => 'Scuole che si esibiscono prima dei finalisti (es: "Scuola di musica di Fiesole fondazione Onlus")',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 1,
			'delay' => 1,
		),
		array(
			'key' => 'field_69c572406d892',
			'label' => 'Esibizione Finalisti',
			'name' => 'finalisti',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => 'Esibizione dei finalisti, nomi in fila. Es:
Mario Rossi, Giovanna Verdi, Luigi Bianchi',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 1,
			'delay' => 1,
		),
		array(
			'key' => 'field_69c572d46d894',
			'label' => 'Giuria',
			'name' => 'giuria',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => 'Nomi dei membri della giuria',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 1,
			'delay' => 1,
		),
		array(
			'key' => 'field_69c572f86d895',
			'label' => 'Commissione di preselezione',
			'name' => 'commissione',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => 'Nomi dei membri della commissione di preselezione',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 1,
			'delay' => 1,
		),
		array(
			'key' => 'field_69c572956d893',
			'label' => 'Altre informazioni',
			'name' => 'altre_informazioni',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => 'Per altre informazioni varie, es: 
A cura di..., In ricordo di...',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 1,
			'delay' => 1,
		),
		array(
			'key' => 'field_69c5735053c86',
			'label' => 'Documenti',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_69c5739253c88',
			'label' => 'Regolamento (testo)',
			'name' => 'regolamento',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 1,
		),
		array(
			'key' => 'field_69c5735b53c87',
			'label' => 'Regolamento (documento scaricabile)',
			'name' => 'regolamento_file',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'pdf, doc, docx',
			'allow_in_bindings' => 0,
		),
		array(
			'key' => 'field_69c573bd53c89',
			'label' => 'Catalogo',
			'name' => 'catalogo_file',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'pdf',
			'allow_in_bindings' => 0,
		),
		array(
			'key' => 'field_69c5784246fab',
			'label' => 'Sponsor',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_69c579910beeb',
			'label' => 'Patrocini',
			'name' => 'lista_patrocini',
			'aria-label' => '',
			'type' => 'gallery',
			'instructions' => 'Loghi degli enti patrocinatori',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min' => '',
			'max' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'png,jpg,jpeg,webp',
			'insert' => 'append',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_69c579d70beec',
			'label' => 'Sostenitori',
			'name' => 'lista_sostenitori',
			'aria-label' => '',
			'type' => 'gallery',
			'instructions' => 'Loghi dei sostenitori privati',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min' => '',
			'max' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => 'png,jpg,jpeg,webp',
			'insert' => 'append',
			'preview_size' => 'medium',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'edizione',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
) );

	acf_add_local_field_group( array(
	'key' => 'group_69c575ec82a6b',
	'title' => 'Campi per Finalisti (POST)',
	'fields' => array(
		array(
			'key' => 'field_69c575ec8b090',
			'label' => 'Vincitore',
			'name' => 'ha_vinto_concorso',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Ha vinto il concorso',
			'default_value' => 0,
			'allow_in_bindings' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_69c57a3d9bee4',
			'label' => 'Posizione in classifica',
			'name' => 'posizione_in_classifica',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '1º classificato – 1ª classificata',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_69c575ec8b090',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'finalista',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
) );

	acf_add_local_field_group( array(
	'key' => 'group_69c5765eb8289',
	'title' => 'Campi per Informazioni Sito (OPTIONS)',
	'fields' => array(
		array(
			'key' => 'field_69c5765fa1891',
			'label' => 'Banner',
			'name' => 'banner',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_69c57686a1892',
					'label' => 'testo',
					'name' => 'testo',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Si ricorda che la data ultima per presentare la propria candidatura è il',
					'allow_in_bindings' => 0,
					'tabs' => 'all',
					'toolbar' => 'basic',
					'media_upload' => 0,
					'delay' => 1,
				),
				array(
					'key' => 'field_69c576c3a1893',
					'label' => 'Banner attivo',
					'name' => 'banner_is_active',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Mostra il banner',
					'default_value' => 0,
					'allow_in_bindings' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
		),
		array(
			'key' => 'field_69c5770655f17',
			'label' => 'Copyright',
			'name' => 'copyright',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Copyright © 2025-2026 Associazione Culturale Wanda Capodaglio | Concorso Nazionale di Teatro',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_69c57723322ab',
			'label' => 'Contatti',
			'name' => 'contatti',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_69c5776a322ac',
					'label' => 'Email',
					'name' => 'email',
					'aria-label' => '',
					'type' => 'email',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_69c57773322ad',
					'label' => 'Numero di telefono',
					'name' => 'numero_di_telefono',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
		array(
			'key' => 'field_69c577bbfce98',
			'label' => 'BANDO',
			'name' => 'bando',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => 'PDF del bando per l\'edizione di quest\'anno',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'pdf, doc, docx',
			'allow_in_bindings' => 0,
		),
		array(
			'key' => 'field_69c57cdd8c59d',
			'label' => 'Testi Homepage',
			'name' => 'homepage',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_69c57cf28c59e',
					'label' => 'Contenuto principale',
					'name' => 'descrizione_del_sito',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
				array(
					'key' => 'field_69c57d3095b24',
					'label' => 'Galleria Foto principale',
					'name' => 'foto_slider_principale',
					'aria-label' => '',
					'type' => 'gallery',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min' => '',
					'max' => '',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'insert' => 'append',
					'preview_size' => 'medium',
				),
				array(
					'key' => 'field_69c57d4e95b25',
					'label' => 'CTA Finale titolo',
					'name' => 'cta_finale_titolo',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_69c57d7695b26',
					'label' => 'CTA Finale testo',
					'name' => 'cta_finale_body',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_69c57d4e95b25',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_69c57d8395b27',
					'label' => 'CTA Finale Foto',
					'name' => 'cta_finale_img',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'allow_in_bindings' => 0,
					'preview_size' => 'medium',
				),
				array(
					'key' => 'field_69c57dba95b29',
					'label' => 'Cta Finale pulsante',
					'name' => 'cta_finale_button_text',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Scopri la storia del Concorso',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_69c57d9495b28',
					'label' => 'Cta Finale LINK',
					'name' => 'cta_finale_link',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_69c57dba95b29',
								'operator' => '!=empty',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'informazioni-sito',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
) );
} );

add_action( 'init', function() {
	register_taxonomy( 'edizioni-concorso', array(
	0 => 'finalista',
	1 => 'giudice',
	2 => 'post',
), array(
	'labels' => array(
		'name' => 'Edizioni Concorso',
		'singular_name' => 'Edizioni Concorso',
		'menu_name' => 'Edizione Concorso',
		'all_items' => 'All Edizione Concorso',
		'edit_item' => 'Edit Edizioni Concorso',
		'view_item' => 'View Edizioni Concorso',
		'update_item' => 'Update Edizioni Concorso',
		'add_new_item' => 'Add New Edizioni Concorso',
		'new_item_name' => 'New Edizioni Concorso Name',
		'search_items' => 'Search Edizione Concorso',
		'popular_items' => 'Popular Edizione Concorso',
		'separate_items_with_commas' => 'Separate edizione concorso with commas',
		'add_or_remove_items' => 'Add or remove edizione concorso',
		'choose_from_most_used' => 'Choose from the most used edizione concorso',
		'not_found' => 'No edizione concorso found',
		'no_terms' => 'No edizione concorso',
		'items_list_navigation' => 'Edizione Concorso list navigation',
		'items_list' => 'Edizione Concorso list',
		'back_to_items' => '← Go to edizione concorso',
		'item_link' => 'Edizioni Concorso Link',
		'item_link_description' => 'A link to a edizioni concorso',
	),
	'public' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
) );
} );

add_action( 'init', function() {
	register_post_type( 'edizione', array(
	'labels' => array(
		'name' => 'Edizioni',
		'singular_name' => 'Edizione',
		'menu_name' => 'Edizioni',
		'all_items' => 'All Edizioni',
		'edit_item' => 'Edit Edizione',
		'view_item' => 'View Edizione',
		'view_items' => 'View Edizioni',
		'add_new_item' => 'Add Edizione',
		'add_new' => 'Add Edizione',
		'new_item' => 'New Edizione',
		'parent_item_colon' => 'Parent Edizione:',
		'search_items' => 'Search Edizioni',
		'not_found' => 'No edizioni found',
		'not_found_in_trash' => 'No edizioni found in Trash',
		'archives' => 'Edizione Archives',
		'attributes' => 'Edizione Attributes',
		'insert_into_item' => 'Insert into edizione',
		'uploaded_to_this_item' => 'Uploaded to this edizione',
		'filter_items_list' => 'Filter edizioni list',
		'filter_by_date' => 'Filter edizioni by date',
		'items_list_navigation' => 'Edizioni list navigation',
		'items_list' => 'Edizioni list',
		'item_published' => 'Edizione published.',
		'item_published_privately' => 'Edizione published privately.',
		'item_reverted_to_draft' => 'Edizione reverted to draft.',
		'item_scheduled' => 'Edizione scheduled.',
		'item_updated' => 'Edizione updated.',
		'item_link' => 'Edizione Link',
		'item_link_description' => 'A link to a edizione.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-tickets-alt',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
		2 => 'thumbnail',
		3 => 'custom-fields',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'finalista', array(
	'labels' => array(
		'name' => 'Finalisti',
		'singular_name' => 'finalista',
		'menu_name' => 'Finalisti',
		'all_items' => 'All Finalisti',
		'edit_item' => 'Edit finalista',
		'view_item' => 'View finalista',
		'view_items' => 'View Finalisti',
		'add_new_item' => 'Add finalista',
		'add_new' => 'Add finalista',
		'new_item' => 'New finalista',
		'parent_item_colon' => 'Parent finalista:',
		'search_items' => 'Search Finalisti',
		'not_found' => 'No finalisti found',
		'not_found_in_trash' => 'No finalisti found in Trash',
		'archives' => 'finalista Archives',
		'attributes' => 'finalista Attributes',
		'insert_into_item' => 'Insert into finalista',
		'uploaded_to_this_item' => 'Uploaded to this finalista',
		'filter_items_list' => 'Filter finalisti list',
		'filter_by_date' => 'Filter finalisti by date',
		'items_list_navigation' => 'Finalisti list navigation',
		'items_list' => 'Finalisti list',
		'item_published' => 'finalista published.',
		'item_published_privately' => 'finalista published privately.',
		'item_reverted_to_draft' => 'finalista reverted to draft.',
		'item_scheduled' => 'finalista scheduled.',
		'item_updated' => 'finalista updated.',
		'item_link' => 'finalista Link',
		'item_link_description' => 'A link to a finalista.',
	),
	'public' => true,
	'exclude_from_search' => true,
	'show_in_nav_menus' => false,
	'show_in_admin_bar' => false,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-admin-users',
	'supports' => array(
		0 => 'title',
		1 => 'excerpt',
		2 => 'thumbnail',
		3 => 'custom-fields',
	),
	'delete_with_user' => false,
) );

	register_post_type( 'giudice', array(
	'labels' => array(
		'name' => 'Giuria',
		'singular_name' => 'Giudice',
		'menu_name' => 'Giuria',
		'all_items' => 'All Giuria',
		'edit_item' => 'Edit Giudice',
		'view_item' => 'View Giudice',
		'view_items' => 'View Giuria',
		'add_new_item' => 'Add Giudice',
		'add_new' => 'Add Giudice',
		'new_item' => 'New Giudice',
		'parent_item_colon' => 'Parent Giudice:',
		'search_items' => 'Search Giuria',
		'not_found' => 'No giuria found',
		'not_found_in_trash' => 'No giuria found in Trash',
		'archives' => 'Giudice Archives',
		'attributes' => 'Giudice Attributes',
		'insert_into_item' => 'Insert into giudice',
		'uploaded_to_this_item' => 'Uploaded to this giudice',
		'filter_items_list' => 'Filter giuria list',
		'filter_by_date' => 'Filter giuria by date',
		'items_list_navigation' => 'Giuria list navigation',
		'items_list' => 'Giuria list',
		'item_published' => 'Giudice published.',
		'item_published_privately' => 'Giudice published privately.',
		'item_reverted_to_draft' => 'Giudice reverted to draft.',
		'item_scheduled' => 'Giudice scheduled.',
		'item_updated' => 'Giudice updated.',
		'item_link' => 'Giudice Link',
		'item_link_description' => 'A link to a giudice.',
	),
	'public' => true,
	'exclude_from_search' => true,
	'show_in_nav_menus' => false,
	'show_in_admin_bar' => false,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-admin-users',
	'supports' => array(
		0 => 'title',
		1 => 'editor',
		2 => 'excerpt',
		3 => 'thumbnail',
		4 => 'custom-fields',
	),
	'taxonomies' => array(
		0 => 'edizioni-concorso',
	),
	'delete_with_user' => false,
) );
} );

add_action( 'acf/init', function() {
	acf_add_options_page( array(
	'page_title' => 'Informazioni sito',
	'menu_slug' => 'informazioni-sito',
	'position' => '',
	'redirect' => false,
	'menu_icon' => array(
		'type' => 'dashicons',
		'value' => 'dashicons-admin-generic',
	),
	'icon_url' => 'dashicons-admin-generic',
) );
} );

